var PAWStats = PAWStats || {};
if (!PAWStats.loaded) {
    alert('PLEASE ADD <script src="PAWStats.js"></script> TO YOUR CODE');
}

PAWStats.showSummarySection = function (name, showTitle) {
    showTitle = (showTitle!==false); // default value is true
    if (showTitle) {
        document.writeln('<h2 Section>Summary - '+name+'<btn onclick="PAWStats.collapseSection(this)">–</btn></h2>');
    }
    
    var t_data = this.createSummaryData(name);
    
    var section = document.createElement('Section-Frame');
    section.appendChild(t_data);
    document.body.appendChild(section);
}

PAWStats.createSummaryData = function (name) {
    var TR, TH, TD;
    var SECTION = document.createElement('section-frame');    
    var INLINE_TABLE = document.createElement('table');
    var CAPTION = INLINE_TABLE.createCaption();
    var HEADER = INLINE_TABLE.createTHead();
    var BODY = INLINE_TABLE.createTBody();
    var FOOTER = INLINE_TABLE.createTFoot();
    var BODY_TR, FOOT_TH, TD;
    var FETCH;

    INLINE_TABLE.className  = 't-data';
    
    TR = HEADER.insertRow(); TR.style.fontWeight='bold';

    TH = TR.insertCell();
    TH.innerHTML=''; TH.style.backgroundColor = '#ECECEC'; TH.className = 'lt';
    TH = TR.insertCell(); TH.className='hdr uniq';
    TH.innerHTML='Unique<br>visitors';
    TH = TR.insertCell(); TH.className='hdr visits';
    TH.innerHTML='Number<br>of visits';
    TH = TR.insertCell(); TH.className='hdr pages';
    TH.innerHTML='Pages';
    TH = TR.insertCell(); TH.className='hdr hits';
    TH.innerHTML='Hits';
    TH = TR.insertCell(); TH.className='hdr bandwidth';
    TH.innerHTML='Bandwidth';

    var data=this.json[name][this.year+''+this.month];
    var FETCH, Visitors, Visits;
    //=== Viewed ===================================
    BODY.className = 'ctr';
    TR = BODY.insertRow();

    TD = TR.insertCell();
    TD.innerHTML='Viewed traffic *';
    TD = TR.insertCell(); 
    Visitors = FETCH = (data.GENERAL.TotalUnique.count * 1);
    TD.innerHTML = '<b>'+FETCH._toLocalNo()+'</b><br>&nbsp;';

    TD = TR.insertCell(); 
    Visits = FETCH = (data.GENERAL.TotalVisits.count * 1);
    TD.innerHTML = '<b>'+FETCH._toLocalNo()+'</b><br>(';
    TD.innerHTML+= (FETCH / Visitors)._toLocalNo(2)
                + ' visits/visitor)';

    TD = TR.insertCell(); 
    FETCH = data.TIME.totals.pages;
    TD.innerHTML = '<b>'+FETCH._toLocalNo()+'</b><br>(';
    TD.innerHTML+= (FETCH / Visits)._toLocalNo(2)
                + ' pages/visit)';

    TD = TR.insertCell(); 
    FETCH = data.TIME.totals.hits;
    TD.innerHTML = '<b>'+FETCH._toLocalNo()+'</b><br>(';
    TD.innerHTML+= (FETCH / Visits)._toLocalNo(2)
                + ' hits/visit)';

    TD = TR.insertCell(); 
    FETCH = (Math.round(
        ( (data.TIME.totals.bandwidth) /1024/1024)
        * 100) / 100);
    TD.innerHTML='<b>'+FETCH._toLocalNo(2);
    TD.innerHTML+=' MB</b><br>(';
    TD.innerHTML+= (FETCH / Visits)._toLocalNo(2)
                + ' MB/visit)';

    //=== Not Viewed ===================================
    TR = BODY.insertRow();

    TD = TR.insertCell();
    TD.innerHTML='Not viewed traffic *';
    
    TD = TR.insertCell(); TD.colSpan = 2;
    TD.innerHTML = '';

    TD = TR.insertCell(); TD.style.fontWeight='bold';
    FETCH = data.TIME.totals.notviewed.pages;
    TD.innerHTML = FETCH._toLocalNo();

    TD = TR.insertCell(); TD.style.fontWeight='bold';
    FETCH = data.TIME.totals.notviewed.hits;
    TD.innerHTML = FETCH._toLocalNo();

    TD = TR.insertCell(); TD.style.fontWeight='bold';
    FETCH = (Math.round(
        (data.TIME.totals.notviewed.bandwidth /1024/1024)
        * 100) / 100);
    TD.innerHTML=FETCH._toLocalNo(2);
    TD.innerHTML+=' MB';
    
    //=== Notes ===================================
    TR = BODY.insertRow();

    TD = TR.insertCell(); TD.colSpan = 10;
    TD.style.whiteSpace='normal';
    TD.innerHTML='* Not viewed traffic is traffic generated by robots, worms, or replies with special HTTP response codes.';

    //=== Sub Header ===================================
    TR = BODY.insertRow();

    TD = TR.insertCell(); TD.colSpan = 10; TD.style.fontWeight='bold';
    TD.innerHTML='Data File Updates Stats:';

    //=== Update Stats ===================================
    TR = BODY.insertRow();
    var LastUpdate = data.GENERAL.LastUpdate;
    
    TD = TR.insertCell();
    var ldt=LastUpdate.date;
    TD.innerHTML+='Last Update:<br>'
        + ldt.substr(0,4)+'-'+ldt.substr(4,2)+'-'+ldt.substr(6,2)
        + ' - ' +ldt.substr(8,2) +':'+ ldt.substr(10,2);

    TD = TR.insertCell();
    TD.innerHTML='Parsed records:<br>' + LastUpdate.parsed._toLocalNo();

    TD = TR.insertCell();
    TD.innerHTML='Old records:<br>' + LastUpdate.oldparsed._toLocalNo();

    TD = TR.insertCell();
    TD.innerHTML='New records:<br>' + LastUpdate.newparsed._toLocalNo();

    TD = TR.insertCell();
    TD.innerHTML='Corrupted:<br>' + LastUpdate.corrupted._toLocalNo();

    TD = TR.insertCell();
    TD.innerHTML='Dropped:<br>' + LastUpdate.dropped._toLocalNo();

    //======================================
    return INLINE_TABLE;
}


